name: PR notification
on:
  push:
jobs:
  fetch_all_pull_request_shas:
    runs-on: ubuntu-latest
    outputs:
      pr_details: ${{ steps.extract.outputs.pr_details }}
    env:
      API_URL: https://api.github.com/repos/redhat-developer/lsp4ij/pulls
    steps:
      - name: Extract PR numbers and merge_commit_shas
        shell: bash
        id: extract
        run: |
          # Fetch PR details from the GitHub API
          pr_infos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ env.API_URL }}")
          
          # Extract PR numbers and merge_commit_sha values, excluding draft pull requests with mergeable_state != "dirty"
          pr_details=$(echo "$pr_infos" | jq -r '[.[] | select(.draft == false and .mergeable_state != "dirty") | {number: .number, sha: .merge_commit_sha}]')
          
          # Initialize an empty JSON array string
          json_array="[]"
          
          echo "Checking mergeable state of PRs..."
          pr_urls=$(echo "$pr_details" | jq -r '.[] | "${{ env.API_URL }}/\(.number)"')
          for url in $pr_urls; do
            pr_detail=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$url")
            mergeable_state=$(echo "$pr_detail" | jq -r '.mergeable_state')
            if [ "$mergeable_state" != "dirty" ]; then
              pr_number=$(echo "$pr_detail" | jq -r '.number')
              pr_sha=$(echo "$pr_detail" | jq -r '.merge_commit_sha')
              # Create a JSON object for the PR number and SHA
              pr_json=$(jq -n --arg number "$pr_number" --arg sha "$pr_sha" '{number: $number, sha: $sha}')
              # Append the JSON object to the JSON array
              json_array=$(echo "$json_array" | jq --argjson pr "$pr_json" '. + [$pr]')
            fi
          done
          
          # Output the JSON array string
          echo "JSON array of PRs without merge conflicts: $json_array"

          # Set the output
          echo "::set-output name=pr_details::$json_array"

  # Run the LTI Tests against each open lsp4ij PRs
  call-build-workflow-for-each-merge-commit-sha:
    needs: fetch_all_pull_request_shas
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux, mac, windows ]
        include:
          - runtime: linux
            os: ubuntu-latest
            reportName: linux-test-report
          - runtime: mac
            os: macOS-latest
            reportName: mac-test-report
          - runtime: windows
            os: windows-latest
            reportName: windows-test-report
        pr_details: ${{ fromJson(needs.fetch_all_pull_request_shas.outputs.pr_details) }}
    name: Run LTI tests for PR #${{ matrix.pr_details.number }}
    steps:
      - name: 'Checkout lsp4ij'
        uses: actions/checkout@v4.1.7
        with:
          repository: redhat-developer/lsp4ij
          path: lsp4ij
          ref: ${{ matrix.pr_details.sha }}
