name: PR notification
on:
  push : 
jobs:
  fetch_all_pull_request_shas:
    runs-on: ubuntu-latest
    outputs:
      pr_details: ${{ steps.extract.outputs.pr_details }}
    env:
      API_URL: https://api.github.com/repos/redhat-developer/lsp4ij/pulls
    steps:
      - name: Extract PR numbers and merge_commit_shas
        id: extract
        run: |
          pr_infos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ env.API_URL }}")

          # Extract PR numbers and merge_commit_sha values, excluding draft pull requests
          pr_details=$(echo "$pr_infos" | jq -r '.[] | select(.draft == false) | {number: .number, sha: .merge_commit_sha, mergeable_state: .mergeable_state}')

          # Print the PR number, merge commit sha, and mergeable state
          echo "PR number, merge commit sha, and mergeable state:"
          echo "$pr_details" | jq -r '. | "PR #\(.number): \(.sha), Mergeable State: \(.mergeable_state)"'

          # Create a JSON array string of PR numbers, SHAs, and mergeable states
          pr_details=$(echo "$pr_details" | jq -nc '[inputs | {number: .number, sha: .sha, mergeable_state: .mergeable_state}]')
          echo "pr_details=$pr_details" >> $GITHUB_ENV

          # Check for mergeable_state "dirty" and set an output if found
          if echo "$pr_details" | jq -e '.[] | select(.mergeable_state == "dirty")' > /dev/null; then
            echo "::warning::One or more PRs have conflicts (mergeable_state: dirty)."
          fi
